{
  imports = [
    ./age.nix
    ./android.nix
    ./base.nix
    ./bluetooth.nix
    ./clojure.nix
    ./compile.nix
    ./direnv.nix
    ./docker.nix
    ./emacs
    ./git.nix
    ./gnupg.nix
    ./gtk.nix
    ./home.nix
    ./irc.nix
    ./keyboard.nix
    ./firefox.nix
    ./fontutils.nix
    ./javascript.nix
    ./mail.nix
    ./markdown.nix
    ./networking.nix
    ./nix.nix
    ./passage.nix
    ./password-store.nix
    ./playerctl.nix
    ./pipewire.nix
    ./qemu.nix
    ./shell
    ./ssh.nix
    ./tailscale.nix
    ./theme.nix
    ./wm
    ./xdg.nix
    ./yaml.nix
  ];
}
